name: deploy site
on: [push]
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: "wasm32-unknown-unknown"
      - uses: Swatinem/rust-cache@v2
      - uses: cargo-bins/cargo-binstall@v1.4.9
      - name: setup
        run: |
          rustup update
          rustup default nightly
          rustup override set nightly
          rustup target add wasm32-unknown-unknown
          cargo install trunk
      - name: build website
        run: |
          trunk build --release --public-url "${GITHUB_REPOSITORY#*/}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
