name: deploy site
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: "wasm32-unknown-unknown"
      - uses: Swatinem/rust-cache@v2
      - uses: cargo-bins/cargo-binstall@v1.4.9
      - name: setup
        run: |
          rustup update
          cargo install cargo-leptos --version=0.2.0
      - name: watch
        run: |
          cargo leptos build --release
